Refactor

diff --git a/.github/workflows/build-blogbot.yml b/.github/workflows/build-blogbot.yml
--- a/.github/workflows/build-blogbot.yml
+++ b/.github/workflows/build-blogbot.yml
@@ -39,26 +39,27 @@ jobs:
         needs: build-tools-blogbot
         runs-on: macos-26
         steps:
+            - name: Checkout repository
+              uses: actions/checkout@v4
             - name: Download binaries
               uses: actions/download-artifact@v4
               with:
                   name: blogbot-binary
-            - name: Install blogbot to /usr/local/bin
-              run: |
-                    ls -la
-                    set -e
-                    # find the binary inside the extracted artifact and move it to /usr/local/bin
-                    BIN_PATH="$(find ./blogbot-binary -type f -name 1bbb -print -quit)"
-                    if [ -z "$BIN_PATH" ]; then
-                        echo "blogbot binary not found"
-                        exit 1
-                    fi
-                    sudo mv "$BIN_PATH" /usr/local/bin/1bbb
-                    sudo chmod +x /usr/local/bin/1bbb
-                    /usr/local/bin/1bbb --version || true
-            - name: Checkout repository
-              uses: actions/checkout@v4
+            # - name: Install blogbot to /usr/local/bin
+            #   run: |
+            #         ls -la
+            #         set -e
+            #         # find the binary inside the extracted artifact and move it to /usr/local/bin
+            #         BIN_PATH="$(find ./blogbot-binary -type f -name 1bbb -print -quit)"
+            #         if [ -z "$BIN_PATH" ]; then
+            #             echo "blogbot binary not found"
+            #             exit 1
+            #         fi
+            #         sudo mv "$BIN_PATH" /usr/local/bin/1bbb
+            #         sudo chmod +x /usr/local/bin/1bbb
+            #         /usr/local/bin/1bbb --version || true
             - name: Deploy blog articles list
               run: |
+                    ls -la
                     chmod +x ./1bbb
                     ./1bbb --repos-file articles.json
